version: '3'
services:
  jenkins_master:
    container_name: jenkins_master
    build: ./master
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home

  jenkins_data:
    container_name: jenkins_data
    build: ./data