version: '3'
services:
  jenkins_master:
    image: jenkin-master
    restart: always
    build: .
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: